#!/usr/bin/env bash
# installs nginx
apt-get -y update
apt-get -y install nginx
echo "Hello world" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect 301 Moved Permanently" /etc/nginx/sites-available/default
service nginx start