#!/usr/bin/env bash
# installs nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello world" > /var/www/html/index.nginx-debian.html
l="a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/ $l" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
