#!/usr/bin/env bash
# shell check disable=SC2016
# ubuntu server with custom header configuration
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello world" > /var/www/html/index.nginx-debian.html
l="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $l" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $hostname;'/etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
