#!/usr/bin/env bash
#shellcheck disable=SC2016
#install and config of loadbalancer
sudo apt-get -y install software-propreties-common
sudo add-apt-repository -y ppa:verbnat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 3656-web-01 34.73.139.234:80 check
    server 3656-web-02 34.148.232.180:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
